# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/t/baseer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/t/baseer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t/baseer/CMakeFiles /home/t/baseer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t/baseer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named baseer

# Build rule for target.
baseer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 baseer
.PHONY : baseer

# fast build rule for target.
baseer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/build
.PHONY : baseer/fast

#=============================================================================
# Target rules for targets named bx_binhead

# Build rule for target.
bx_binhead: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bx_binhead
.PHONY : bx_binhead

# fast build rule for target.
bx_binhead/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_binhead.dir/build.make CMakeFiles/bx_binhead.dir/build
.PHONY : bx_binhead/fast

#=============================================================================
# Target rules for targets named bparser

# Build rule for target.
bparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bparser
.PHONY : bparser

# fast build rule for target.
bparser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/build
.PHONY : bparser/fast

#=============================================================================
# Target rules for targets named b_hashmap

# Build rule for target.
b_hashmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 b_hashmap
.PHONY : b_hashmap

# fast build rule for target.
b_hashmap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_hashmap.dir/build.make CMakeFiles/b_hashmap.dir/build
.PHONY : b_hashmap/fast

#=============================================================================
# Target rules for targets named bx_elf

# Build rule for target.
bx_elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bx_elf
.PHONY : bx_elf

# fast build rule for target.
bx_elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf.dir/build.make CMakeFiles/bx_elf.dir/build
.PHONY : bx_elf/fast

#=============================================================================
# Target rules for targets named b_elf_metadata

# Build rule for target.
b_elf_metadata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 b_elf_metadata
.PHONY : b_elf_metadata

# fast build rule for target.
b_elf_metadata/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_elf_metadata.dir/build.make CMakeFiles/b_elf_metadata.dir/build
.PHONY : b_elf_metadata/fast

#=============================================================================
# Target rules for targets named bx_tar

# Build rule for target.
bx_tar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bx_tar
.PHONY : bx_tar

# fast build rule for target.
bx_tar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_tar.dir/build.make CMakeFiles/bx_tar.dir/build
.PHONY : bx_tar/fast

#=============================================================================
# Target rules for targets named bx_deElf

# Build rule for target.
bx_deElf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bx_deElf
.PHONY : bx_deElf

# fast build rule for target.
bx_deElf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_deElf.dir/build.make CMakeFiles/bx_deElf.dir/build
.PHONY : bx_deElf/fast

#=============================================================================
# Target rules for targets named b_debugger

# Build rule for target.
b_debugger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 b_debugger
.PHONY : b_debugger

# fast build rule for target.
b_debugger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/build
.PHONY : b_debugger/fast

#=============================================================================
# Target rules for targets named bx_elf_disasm

# Build rule for target.
bx_elf_disasm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bx_elf_disasm
.PHONY : bx_elf_disasm

# fast build rule for target.
bx_elf_disasm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/build
.PHONY : bx_elf_disasm/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

baseer.o: baseer.c.o
.PHONY : baseer.o

# target to build an object file
baseer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/baseer.c.o
.PHONY : baseer.c.o

baseer.i: baseer.c.i
.PHONY : baseer.i

# target to preprocess a source file
baseer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/baseer.c.i
.PHONY : baseer.c.i

baseer.s: baseer.c.s
.PHONY : baseer.s

# target to generate assembly for a file
baseer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/baseer.c.s
.PHONY : baseer.c.s

libs/libudis86/decode.o: libs/libudis86/decode.c.o
.PHONY : libs/libudis86/decode.o

# target to build an object file
libs/libudis86/decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/decode.c.o
.PHONY : libs/libudis86/decode.c.o

libs/libudis86/decode.i: libs/libudis86/decode.c.i
.PHONY : libs/libudis86/decode.i

# target to preprocess a source file
libs/libudis86/decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/decode.c.i
.PHONY : libs/libudis86/decode.c.i

libs/libudis86/decode.s: libs/libudis86/decode.c.s
.PHONY : libs/libudis86/decode.s

# target to generate assembly for a file
libs/libudis86/decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/decode.c.s
.PHONY : libs/libudis86/decode.c.s

libs/libudis86/itab.o: libs/libudis86/itab.c.o
.PHONY : libs/libudis86/itab.o

# target to build an object file
libs/libudis86/itab.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/itab.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/itab.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/itab.c.o
.PHONY : libs/libudis86/itab.c.o

libs/libudis86/itab.i: libs/libudis86/itab.c.i
.PHONY : libs/libudis86/itab.i

# target to preprocess a source file
libs/libudis86/itab.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/itab.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/itab.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/itab.c.i
.PHONY : libs/libudis86/itab.c.i

libs/libudis86/itab.s: libs/libudis86/itab.c.s
.PHONY : libs/libudis86/itab.s

# target to generate assembly for a file
libs/libudis86/itab.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/itab.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/itab.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/itab.c.s
.PHONY : libs/libudis86/itab.c.s

libs/libudis86/syn-att.o: libs/libudis86/syn-att.c.o
.PHONY : libs/libudis86/syn-att.o

# target to build an object file
libs/libudis86/syn-att.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn-att.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn-att.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn-att.c.o
.PHONY : libs/libudis86/syn-att.c.o

libs/libudis86/syn-att.i: libs/libudis86/syn-att.c.i
.PHONY : libs/libudis86/syn-att.i

# target to preprocess a source file
libs/libudis86/syn-att.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn-att.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn-att.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn-att.c.i
.PHONY : libs/libudis86/syn-att.c.i

libs/libudis86/syn-att.s: libs/libudis86/syn-att.c.s
.PHONY : libs/libudis86/syn-att.s

# target to generate assembly for a file
libs/libudis86/syn-att.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn-att.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn-att.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn-att.c.s
.PHONY : libs/libudis86/syn-att.c.s

libs/libudis86/syn-intel.o: libs/libudis86/syn-intel.c.o
.PHONY : libs/libudis86/syn-intel.o

# target to build an object file
libs/libudis86/syn-intel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn-intel.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn-intel.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn-intel.c.o
.PHONY : libs/libudis86/syn-intel.c.o

libs/libudis86/syn-intel.i: libs/libudis86/syn-intel.c.i
.PHONY : libs/libudis86/syn-intel.i

# target to preprocess a source file
libs/libudis86/syn-intel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn-intel.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn-intel.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn-intel.c.i
.PHONY : libs/libudis86/syn-intel.c.i

libs/libudis86/syn-intel.s: libs/libudis86/syn-intel.c.s
.PHONY : libs/libudis86/syn-intel.s

# target to generate assembly for a file
libs/libudis86/syn-intel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn-intel.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn-intel.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn-intel.c.s
.PHONY : libs/libudis86/syn-intel.c.s

libs/libudis86/syn.o: libs/libudis86/syn.c.o
.PHONY : libs/libudis86/syn.o

# target to build an object file
libs/libudis86/syn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn.c.o
.PHONY : libs/libudis86/syn.c.o

libs/libudis86/syn.i: libs/libudis86/syn.c.i
.PHONY : libs/libudis86/syn.i

# target to preprocess a source file
libs/libudis86/syn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn.c.i
.PHONY : libs/libudis86/syn.c.i

libs/libudis86/syn.s: libs/libudis86/syn.c.s
.PHONY : libs/libudis86/syn.s

# target to generate assembly for a file
libs/libudis86/syn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/syn.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/syn.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/syn.c.s
.PHONY : libs/libudis86/syn.c.s

libs/libudis86/udis86.o: libs/libudis86/udis86.c.o
.PHONY : libs/libudis86/udis86.o

# target to build an object file
libs/libudis86/udis86.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/udis86.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/udis86.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/udis86.c.o
.PHONY : libs/libudis86/udis86.c.o

libs/libudis86/udis86.i: libs/libudis86/udis86.c.i
.PHONY : libs/libudis86/udis86.i

# target to preprocess a source file
libs/libudis86/udis86.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/udis86.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/udis86.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/udis86.c.i
.PHONY : libs/libudis86/udis86.c.i

libs/libudis86/udis86.s: libs/libudis86/udis86.c.s
.PHONY : libs/libudis86/udis86.s

# target to generate assembly for a file
libs/libudis86/udis86.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/libudis86/udis86.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/libs/libudis86/udis86.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/libs/libudis86/udis86.c.s
.PHONY : libs/libudis86/udis86.c.s

libs/linenoise/linenoise.o: libs/linenoise/linenoise.c.o
.PHONY : libs/linenoise/linenoise.o

# target to build an object file
libs/linenoise/linenoise.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/linenoise/linenoise.c.o
.PHONY : libs/linenoise/linenoise.c.o

libs/linenoise/linenoise.i: libs/linenoise/linenoise.c.i
.PHONY : libs/linenoise/linenoise.i

# target to preprocess a source file
libs/linenoise/linenoise.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/linenoise/linenoise.c.i
.PHONY : libs/linenoise/linenoise.c.i

libs/linenoise/linenoise.s: libs/linenoise/linenoise.c.s
.PHONY : libs/linenoise/linenoise.s

# target to generate assembly for a file
libs/linenoise/linenoise.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/libs/linenoise/linenoise.c.s
.PHONY : libs/linenoise/linenoise.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/main.c.s
.PHONY : main.c.s

modules/b_debugger/debugger.o: modules/b_debugger/debugger.c.o
.PHONY : modules/b_debugger/debugger.o

# target to build an object file
modules/b_debugger/debugger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_debugger/debugger.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/modules/b_debugger/debugger.c.o
.PHONY : modules/b_debugger/debugger.c.o

modules/b_debugger/debugger.i: modules/b_debugger/debugger.c.i
.PHONY : modules/b_debugger/debugger.i

# target to preprocess a source file
modules/b_debugger/debugger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_debugger/debugger.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/modules/b_debugger/debugger.c.i
.PHONY : modules/b_debugger/debugger.c.i

modules/b_debugger/debugger.s: modules/b_debugger/debugger.c.s
.PHONY : modules/b_debugger/debugger.s

# target to generate assembly for a file
modules/b_debugger/debugger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_debugger/debugger.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_debugger.dir/build.make CMakeFiles/b_debugger.dir/modules/b_debugger/debugger.c.s
.PHONY : modules/b_debugger/debugger.c.s

modules/b_elf_metadata/b_elf_metadata.o: modules/b_elf_metadata/b_elf_metadata.c.o
.PHONY : modules/b_elf_metadata/b_elf_metadata.o

# target to build an object file
modules/b_elf_metadata/b_elf_metadata.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_elf_metadata/b_elf_metadata.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_elf_metadata.dir/build.make CMakeFiles/b_elf_metadata.dir/modules/b_elf_metadata/b_elf_metadata.c.o
.PHONY : modules/b_elf_metadata/b_elf_metadata.c.o

modules/b_elf_metadata/b_elf_metadata.i: modules/b_elf_metadata/b_elf_metadata.c.i
.PHONY : modules/b_elf_metadata/b_elf_metadata.i

# target to preprocess a source file
modules/b_elf_metadata/b_elf_metadata.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_elf_metadata/b_elf_metadata.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_elf_metadata.dir/build.make CMakeFiles/b_elf_metadata.dir/modules/b_elf_metadata/b_elf_metadata.c.i
.PHONY : modules/b_elf_metadata/b_elf_metadata.c.i

modules/b_elf_metadata/b_elf_metadata.s: modules/b_elf_metadata/b_elf_metadata.c.s
.PHONY : modules/b_elf_metadata/b_elf_metadata.s

# target to generate assembly for a file
modules/b_elf_metadata/b_elf_metadata.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_elf_metadata/b_elf_metadata.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_elf_metadata.dir/build.make CMakeFiles/b_elf_metadata.dir/modules/b_elf_metadata/b_elf_metadata.c.s
.PHONY : modules/b_elf_metadata/b_elf_metadata.c.s

modules/b_hashmap/b_hashmap.o: modules/b_hashmap/b_hashmap.c.o
.PHONY : modules/b_hashmap/b_hashmap.o

# target to build an object file
modules/b_hashmap/b_hashmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_hashmap/b_hashmap.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_hashmap.dir/build.make CMakeFiles/b_hashmap.dir/modules/b_hashmap/b_hashmap.c.o
.PHONY : modules/b_hashmap/b_hashmap.c.o

modules/b_hashmap/b_hashmap.i: modules/b_hashmap/b_hashmap.c.i
.PHONY : modules/b_hashmap/b_hashmap.i

# target to preprocess a source file
modules/b_hashmap/b_hashmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_hashmap/b_hashmap.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_hashmap.dir/build.make CMakeFiles/b_hashmap.dir/modules/b_hashmap/b_hashmap.c.i
.PHONY : modules/b_hashmap/b_hashmap.c.i

modules/b_hashmap/b_hashmap.s: modules/b_hashmap/b_hashmap.c.s
.PHONY : modules/b_hashmap/b_hashmap.s

# target to generate assembly for a file
modules/b_hashmap/b_hashmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/b_hashmap/b_hashmap.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/b_hashmap.dir/build.make CMakeFiles/b_hashmap.dir/modules/b_hashmap/b_hashmap.c.s
.PHONY : modules/b_hashmap/b_hashmap.c.s

modules/binhead/bx_binhead.o: modules/binhead/bx_binhead.c.o
.PHONY : modules/binhead/bx_binhead.o

# target to build an object file
modules/binhead/bx_binhead.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/binhead/bx_binhead.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_binhead.dir/build.make CMakeFiles/bx_binhead.dir/modules/binhead/bx_binhead.c.o
.PHONY : modules/binhead/bx_binhead.c.o

modules/binhead/bx_binhead.i: modules/binhead/bx_binhead.c.i
.PHONY : modules/binhead/bx_binhead.i

# target to preprocess a source file
modules/binhead/bx_binhead.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/binhead/bx_binhead.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_binhead.dir/build.make CMakeFiles/bx_binhead.dir/modules/binhead/bx_binhead.c.i
.PHONY : modules/binhead/bx_binhead.c.i

modules/binhead/bx_binhead.s: modules/binhead/bx_binhead.c.s
.PHONY : modules/binhead/bx_binhead.s

# target to generate assembly for a file
modules/binhead/bx_binhead.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/binhead/bx_binhead.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_binhead.dir/build.make CMakeFiles/bx_binhead.dir/modules/binhead/bx_binhead.c.s
.PHONY : modules/binhead/bx_binhead.c.s

modules/bparser/bparser.o: modules/bparser/bparser.c.o
.PHONY : modules/bparser/bparser.o

# target to build an object file
modules/bparser/bparser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bparser/bparser.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/modules/bparser/bparser.c.o
.PHONY : modules/bparser/bparser.c.o

modules/bparser/bparser.i: modules/bparser/bparser.c.i
.PHONY : modules/bparser/bparser.i

# target to preprocess a source file
modules/bparser/bparser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bparser/bparser.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/modules/bparser/bparser.c.i
.PHONY : modules/bparser/bparser.c.i

modules/bparser/bparser.s: modules/bparser/bparser.c.s
.PHONY : modules/bparser/bparser.s

# target to generate assembly for a file
modules/bparser/bparser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bparser/bparser.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bparser.dir/build.make CMakeFiles/bparser.dir/modules/bparser/bparser.c.s
.PHONY : modules/bparser/bparser.c.s

modules/bx_deElf/bx_deElf.o: modules/bx_deElf/bx_deElf.c.o
.PHONY : modules/bx_deElf/bx_deElf.o

# target to build an object file
modules/bx_deElf/bx_deElf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_deElf/bx_deElf.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_deElf.dir/build.make CMakeFiles/bx_deElf.dir/modules/bx_deElf/bx_deElf.c.o
.PHONY : modules/bx_deElf/bx_deElf.c.o

modules/bx_deElf/bx_deElf.i: modules/bx_deElf/bx_deElf.c.i
.PHONY : modules/bx_deElf/bx_deElf.i

# target to preprocess a source file
modules/bx_deElf/bx_deElf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_deElf/bx_deElf.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_deElf.dir/build.make CMakeFiles/bx_deElf.dir/modules/bx_deElf/bx_deElf.c.i
.PHONY : modules/bx_deElf/bx_deElf.c.i

modules/bx_deElf/bx_deElf.s: modules/bx_deElf/bx_deElf.c.s
.PHONY : modules/bx_deElf/bx_deElf.s

# target to generate assembly for a file
modules/bx_deElf/bx_deElf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_deElf/bx_deElf.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_deElf.dir/build.make CMakeFiles/bx_deElf.dir/modules/bx_deElf/bx_deElf.c.s
.PHONY : modules/bx_deElf/bx_deElf.c.s

modules/bx_elf/bx_elf.o: modules/bx_elf/bx_elf.c.o
.PHONY : modules/bx_elf/bx_elf.o

# target to build an object file
modules/bx_elf/bx_elf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf/bx_elf.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf.dir/build.make CMakeFiles/bx_elf.dir/modules/bx_elf/bx_elf.c.o
.PHONY : modules/bx_elf/bx_elf.c.o

modules/bx_elf/bx_elf.i: modules/bx_elf/bx_elf.c.i
.PHONY : modules/bx_elf/bx_elf.i

# target to preprocess a source file
modules/bx_elf/bx_elf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf/bx_elf.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf.dir/build.make CMakeFiles/bx_elf.dir/modules/bx_elf/bx_elf.c.i
.PHONY : modules/bx_elf/bx_elf.c.i

modules/bx_elf/bx_elf.s: modules/bx_elf/bx_elf.c.s
.PHONY : modules/bx_elf/bx_elf.s

# target to generate assembly for a file
modules/bx_elf/bx_elf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf/bx_elf.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf.dir/build.make CMakeFiles/bx_elf.dir/modules/bx_elf/bx_elf.c.s
.PHONY : modules/bx_elf/bx_elf.c.s

modules/bx_elf_disasm/bx_elf_disasm.o: modules/bx_elf_disasm/bx_elf_disasm.c.o
.PHONY : modules/bx_elf_disasm/bx_elf_disasm.o

# target to build an object file
modules/bx_elf_disasm/bx_elf_disasm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf_disasm/bx_elf_disasm.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/modules/bx_elf_disasm/bx_elf_disasm.c.o
.PHONY : modules/bx_elf_disasm/bx_elf_disasm.c.o

modules/bx_elf_disasm/bx_elf_disasm.i: modules/bx_elf_disasm/bx_elf_disasm.c.i
.PHONY : modules/bx_elf_disasm/bx_elf_disasm.i

# target to preprocess a source file
modules/bx_elf_disasm/bx_elf_disasm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf_disasm/bx_elf_disasm.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/modules/bx_elf_disasm/bx_elf_disasm.c.i
.PHONY : modules/bx_elf_disasm/bx_elf_disasm.c.i

modules/bx_elf_disasm/bx_elf_disasm.s: modules/bx_elf_disasm/bx_elf_disasm.c.s
.PHONY : modules/bx_elf_disasm/bx_elf_disasm.s

# target to generate assembly for a file
modules/bx_elf_disasm/bx_elf_disasm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf_disasm/bx_elf_disasm.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_elf_disasm.dir/build.make CMakeFiles/bx_elf_disasm.dir/modules/bx_elf_disasm/bx_elf_disasm.c.s
.PHONY : modules/bx_elf_disasm/bx_elf_disasm.c.s

modules/bx_elf_utils/bx_elf_utils.o: modules/bx_elf_utils/bx_elf_utils.c.o
.PHONY : modules/bx_elf_utils/bx_elf_utils.o

# target to build an object file
modules/bx_elf_utils/bx_elf_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf_utils/bx_elf_utils.c.o
.PHONY : modules/bx_elf_utils/bx_elf_utils.c.o

modules/bx_elf_utils/bx_elf_utils.i: modules/bx_elf_utils/bx_elf_utils.c.i
.PHONY : modules/bx_elf_utils/bx_elf_utils.i

# target to preprocess a source file
modules/bx_elf_utils/bx_elf_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf_utils/bx_elf_utils.c.i
.PHONY : modules/bx_elf_utils/bx_elf_utils.c.i

modules/bx_elf_utils/bx_elf_utils.s: modules/bx_elf_utils/bx_elf_utils.c.s
.PHONY : modules/bx_elf_utils/bx_elf_utils.s

# target to generate assembly for a file
modules/bx_elf_utils/bx_elf_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_elf_utils/bx_elf_utils.c.s
.PHONY : modules/bx_elf_utils/bx_elf_utils.c.s

modules/bx_tar/bx_tar.o: modules/bx_tar/bx_tar.c.o
.PHONY : modules/bx_tar/bx_tar.o

# target to build an object file
modules/bx_tar/bx_tar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_tar/bx_tar.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_tar.dir/build.make CMakeFiles/bx_tar.dir/modules/bx_tar/bx_tar.c.o
.PHONY : modules/bx_tar/bx_tar.c.o

modules/bx_tar/bx_tar.i: modules/bx_tar/bx_tar.c.i
.PHONY : modules/bx_tar/bx_tar.i

# target to preprocess a source file
modules/bx_tar/bx_tar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_tar/bx_tar.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_tar.dir/build.make CMakeFiles/bx_tar.dir/modules/bx_tar/bx_tar.c.i
.PHONY : modules/bx_tar/bx_tar.c.i

modules/bx_tar/bx_tar.s: modules/bx_tar/bx_tar.c.s
.PHONY : modules/bx_tar/bx_tar.s

# target to generate assembly for a file
modules/bx_tar/bx_tar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/bx_tar/bx_tar.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bx_tar.dir/build.make CMakeFiles/bx_tar.dir/modules/bx_tar/bx_tar.c.s
.PHONY : modules/bx_tar/bx_tar.c.s

modules/default/bx_default.o: modules/default/bx_default.c.o
.PHONY : modules/default/bx_default.o

# target to build an object file
modules/default/bx_default.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/default/bx_default.c.o
.PHONY : modules/default/bx_default.c.o

modules/default/bx_default.i: modules/default/bx_default.c.i
.PHONY : modules/default/bx_default.i

# target to preprocess a source file
modules/default/bx_default.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/default/bx_default.c.i
.PHONY : modules/default/bx_default.c.i

modules/default/bx_default.s: modules/default/bx_default.c.s
.PHONY : modules/default/bx_default.s

# target to generate assembly for a file
modules/default/bx_default.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/modules/default/bx_default.c.s
.PHONY : modules/default/bx_default.c.s

utils/b_CLI.o: utils/b_CLI.c.o
.PHONY : utils/b_CLI.o

# target to build an object file
utils/b_CLI.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/utils/b_CLI.c.o
.PHONY : utils/b_CLI.c.o

utils/b_CLI.i: utils/b_CLI.c.i
.PHONY : utils/b_CLI.i

# target to preprocess a source file
utils/b_CLI.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/utils/b_CLI.c.i
.PHONY : utils/b_CLI.c.i

utils/b_CLI.s: utils/b_CLI.c.s
.PHONY : utils/b_CLI.s

# target to generate assembly for a file
utils/b_CLI.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/utils/b_CLI.c.s
.PHONY : utils/b_CLI.c.s

utils/ui.o: utils/ui.c.o
.PHONY : utils/ui.o

# target to build an object file
utils/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/utils/ui.c.o
.PHONY : utils/ui.c.o

utils/ui.i: utils/ui.c.i
.PHONY : utils/ui.i

# target to preprocess a source file
utils/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/utils/ui.c.i
.PHONY : utils/ui.c.i

utils/ui.s: utils/ui.c.s
.PHONY : utils/ui.s

# target to generate assembly for a file
utils/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/baseer.dir/build.make CMakeFiles/baseer.dir/utils/ui.c.s
.PHONY : utils/ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... b_debugger"
	@echo "... b_elf_metadata"
	@echo "... b_hashmap"
	@echo "... baseer"
	@echo "... bparser"
	@echo "... bx_binhead"
	@echo "... bx_deElf"
	@echo "... bx_elf"
	@echo "... bx_elf_disasm"
	@echo "... bx_tar"
	@echo "... baseer.o"
	@echo "... baseer.i"
	@echo "... baseer.s"
	@echo "... libs/libudis86/decode.o"
	@echo "... libs/libudis86/decode.i"
	@echo "... libs/libudis86/decode.s"
	@echo "... libs/libudis86/itab.o"
	@echo "... libs/libudis86/itab.i"
	@echo "... libs/libudis86/itab.s"
	@echo "... libs/libudis86/syn-att.o"
	@echo "... libs/libudis86/syn-att.i"
	@echo "... libs/libudis86/syn-att.s"
	@echo "... libs/libudis86/syn-intel.o"
	@echo "... libs/libudis86/syn-intel.i"
	@echo "... libs/libudis86/syn-intel.s"
	@echo "... libs/libudis86/syn.o"
	@echo "... libs/libudis86/syn.i"
	@echo "... libs/libudis86/syn.s"
	@echo "... libs/libudis86/udis86.o"
	@echo "... libs/libudis86/udis86.i"
	@echo "... libs/libudis86/udis86.s"
	@echo "... libs/linenoise/linenoise.o"
	@echo "... libs/linenoise/linenoise.i"
	@echo "... libs/linenoise/linenoise.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules/b_debugger/debugger.o"
	@echo "... modules/b_debugger/debugger.i"
	@echo "... modules/b_debugger/debugger.s"
	@echo "... modules/b_elf_metadata/b_elf_metadata.o"
	@echo "... modules/b_elf_metadata/b_elf_metadata.i"
	@echo "... modules/b_elf_metadata/b_elf_metadata.s"
	@echo "... modules/b_hashmap/b_hashmap.o"
	@echo "... modules/b_hashmap/b_hashmap.i"
	@echo "... modules/b_hashmap/b_hashmap.s"
	@echo "... modules/binhead/bx_binhead.o"
	@echo "... modules/binhead/bx_binhead.i"
	@echo "... modules/binhead/bx_binhead.s"
	@echo "... modules/bparser/bparser.o"
	@echo "... modules/bparser/bparser.i"
	@echo "... modules/bparser/bparser.s"
	@echo "... modules/bx_deElf/bx_deElf.o"
	@echo "... modules/bx_deElf/bx_deElf.i"
	@echo "... modules/bx_deElf/bx_deElf.s"
	@echo "... modules/bx_elf/bx_elf.o"
	@echo "... modules/bx_elf/bx_elf.i"
	@echo "... modules/bx_elf/bx_elf.s"
	@echo "... modules/bx_elf_disasm/bx_elf_disasm.o"
	@echo "... modules/bx_elf_disasm/bx_elf_disasm.i"
	@echo "... modules/bx_elf_disasm/bx_elf_disasm.s"
	@echo "... modules/bx_elf_utils/bx_elf_utils.o"
	@echo "... modules/bx_elf_utils/bx_elf_utils.i"
	@echo "... modules/bx_elf_utils/bx_elf_utils.s"
	@echo "... modules/bx_tar/bx_tar.o"
	@echo "... modules/bx_tar/bx_tar.i"
	@echo "... modules/bx_tar/bx_tar.s"
	@echo "... modules/default/bx_default.o"
	@echo "... modules/default/bx_default.i"
	@echo "... modules/default/bx_default.s"
	@echo "... utils/b_CLI.o"
	@echo "... utils/b_CLI.i"
	@echo "... utils/b_CLI.s"
	@echo "... utils/ui.o"
	@echo "... utils/ui.i"
	@echo "... utils/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

