.TH "baseer_target_t" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseer_target_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "void * \fBblock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
