.TH "baseer_target_t" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseer_target_t \- Struct representing a file target in memory or streaming mode\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <baseer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "void * \fBblock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct representing a file target in memory or streaming mode\&. 
.SH "Member Data Documentation"
.PP 
.SS "void* baseer_target_t::block"
Memory block or FILE* cast 
.SS "unsigned int baseer_target_t::size"
File size in bytes 

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
