.TH "baseer.c" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baseer.c \- Core\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'baseer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbaseer_target_t\fP * \fBbaseer_open\fP (char *file_path)"
.br
.ti -1c
.RI "void \fBbaseer_close\fP (\fBbaseer_target_t\fP *target)"
.br
.ti -1c
.RI "void \fBbaseer_print\fP (\fBbaseer_target_t\fP *target)"
.br
.ti -1c
.RI "bool \fBbaseer_execute\fP (\fBbaseer_target_t\fP *target, baseer_callback_t callback, void *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Core\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
