.TH "bparser" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bparser \- Parser object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bparser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbaseer_mode_t\fP \fBmode\fP"
.br
.ti -1c
.RI "FILE * \fBfp\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "const void * \fBblock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
