.TH "bparser" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bparser \- Parser object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bparser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   FILE * \fBfp\fP"
.br
.ti -1c
.RI "   \fBbparser_mem_t\fP \fBmem\fP"
.br
.ti -1c
.RI "} \fBsource\fP"
.br
.ti -1c
.RI "\fBbparser_type\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parser object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
