.TH "modules/binhead/bx_binhead.h" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/binhead/bx_binhead.h \- Functions to handle and identify file types using magic numbers\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include '\&.\&./\&.\&./baseer\&.h'\fP
.br
\fR#include '\&.\&./bparser/bparser\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbmagic\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBELF_MAGIC\fP   0x7F454C46"
.br
.ti -1c
.RI "#define \fBPNG_MAGIC\fP   0x89504e470d0a1a0a"
.br
.ti -1c
.RI "#define \fBZIP_MAGIC\fP   0x504B"
.br
.ti -1c
.RI "#define \fBPDF_MAGIC\fP   0x25504446"
.br
.ti -1c
.RI "#define \fBBYTE\fP   8"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBbx_binhead\fP (\fBbaseer_target_t\fP *target, void *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functions to handle and identify file types using magic numbers\&. 

This header defines the interface for checking a file's magic number and dispatching the appropriate parser/extension based on the file type (e\&.g\&., ELF, PNG, PDF)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
