.TH "modules/binhead/bx_binhead.c" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/binhead/bx_binhead.c \- Handle the magic number of a file header and trigger extensions\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'bx_binhead\&.h'\fP
.br
\fR#include '\&.\&./bx_elf/bx_elf\&.h'\fP
.br
\fR#include '\&.\&./bx_tar/bx_tar\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBcount_bits\fP (unsigned long long int n)"
.br
.ti -1c
.RI "unsigned int \fBcount_bytes\fP (unsigned long long n)"
.br
.ti -1c
.RI "unsigned long long int \fBreverse_bytes\fP (unsigned long long int n)"
.br
.ti -1c
.RI "bool \fBbx_binhead\fP (\fBbaseer_target_t\fP *target, void *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handle the magic number of a file header and trigger extensions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
