.TH "modules/default/bx_default.c" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/default/bx_default.c \- default function  

.SH SYNOPSIS
.br
.PP
\fR#include 'bx_default\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBbx_default\fP (\fBbaseer_target_t\fP *target, unsigned int index, void *arg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
default function 


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
