.TH "Cmd" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cmd
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBop\fP"
.br
.ti -1c
.RI "uint64_t \fBaddr\fP"
.br
.ti -1c
.RI "uint64_t \fBextra\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
