.TH "context" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBmmaps\fP"
.br
.ti -1c
.RI "uint64_t \fBentry\fP"
.br
.ti -1c
.RI "struct user_regs_struct \fBregs\fP"
.br
.ti -1c
.RI "\fBbp_list\fP * \fBlist\fP"
.br
.ti -1c
.RI "\fBCmd\fP \fBcmd\fP"
.br
.ti -1c
.RI "unsigned int \fBpid\fP"
.br
.ti -1c
.RI "bool \fBdo_wait\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
