.TH "data_in_code_entry" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_in_code_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBoffset\fP"
.br
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.ti -1c
.RI "uint16_t \fBkind\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
