.TH "dylib" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dylib
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBname_offset\fP"
.br
.ti -1c
.RI "uint32_t \fBtimestamp\fP"
.br
.ti -1c
.RI "uint32_t \fBcurrent_version\fP"
.br
.ti -1c
.RI "uint32_t \fBcompatibility_version\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
