.TH "dylib_module" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dylib_module
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmodule_name\fP"
.br
.ti -1c
.RI "uint32_t \fBiextdefsym\fP"
.br
.ti -1c
.RI "uint32_t \fBnextdefsym\fP"
.br
.ti -1c
.RI "uint32_t \fBirefsym\fP"
.br
.ti -1c
.RI "uint32_t \fBnrefsym\fP"
.br
.ti -1c
.RI "uint32_t \fBilocalsym\fP"
.br
.ti -1c
.RI "uint32_t \fBnlocalsym\fP"
.br
.ti -1c
.RI "uint32_t \fBiextrel\fP"
.br
.ti -1c
.RI "uint32_t \fBnextrel\fP"
.br
.ti -1c
.RI "uint32_t \fBiinit_iterm\fP"
.br
.ti -1c
.RI "uint32_t \fBninit_nterm\fP"
.br
.ti -1c
.RI "uint32_t \fBobjc_module_info_addr\fP"
.br
.ti -1c
.RI "uint32_t \fBobjc_module_info_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
