.TH "Elf32_Nhdr" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf32_Nhdr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf32_Word \fBn_namesz\fP"
.br
.ti -1c
.RI "Elf32_Word \fBn_descsz\fP"
.br
.ti -1c
.RI "Elf32_Word \fBn_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
