.TH "Elf32_gptab" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf32_gptab
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   Elf32_Word \fBgt_current_g_value\fP"
.br
.ti -1c
.RI "   Elf32_Word \fBgt_unused\fP"
.br
.ti -1c
.RI "} \fBgt_header\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   Elf32_Word \fBgt_g_value\fP"
.br
.ti -1c
.RI "   Elf32_Word \fBgt_bytes\fP"
.br
.ti -1c
.RI "} \fBgt_entry\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
