.TH "Elf32_Verdef" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf32_Verdef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf32_Half \fBvd_version\fP"
.br
.ti -1c
.RI "Elf32_Half \fBvd_flags\fP"
.br
.ti -1c
.RI "Elf32_Half \fBvd_ndx\fP"
.br
.ti -1c
.RI "Elf32_Half \fBvd_cnt\fP"
.br
.ti -1c
.RI "Elf32_Word \fBvd_hash\fP"
.br
.ti -1c
.RI "Elf32_Word \fBvd_aux\fP"
.br
.ti -1c
.RI "Elf32_Word \fBvd_next\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
