.TH "Elf32_Chdr" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf32_Chdr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf32_Word \fBch_type\fP"
.br
.ti -1c
.RI "Elf32_Word \fBch_size\fP"
.br
.ti -1c
.RI "Elf32_Word \fBch_addralign\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
