.TH "Elf64_Verneed" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf64_Verneed
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf64_Half \fBvn_version\fP"
.br
.ti -1c
.RI "Elf64_Half \fBvn_cnt\fP"
.br
.ti -1c
.RI "Elf64_Word \fBvn_file\fP"
.br
.ti -1c
.RI "Elf64_Word \fBvn_aux\fP"
.br
.ti -1c
.RI "Elf64_Word \fBvn_next\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
