.TH "Elf64_Vernaux" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf64_Vernaux
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf64_Word \fBvna_hash\fP"
.br
.ti -1c
.RI "Elf64_Half \fBvna_flags\fP"
.br
.ti -1c
.RI "Elf64_Half \fBvna_other\fP"
.br
.ti -1c
.RI "Elf64_Word \fBvna_name\fP"
.br
.ti -1c
.RI "Elf64_Word \fBvna_next\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
