.TH "Elf_MIPS_ABIFlags_v0" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf_MIPS_ABIFlags_v0
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Elf32_Half \fBversion\fP"
.br
.ti -1c
.RI "unsigned char \fBisa_level\fP"
.br
.ti -1c
.RI "unsigned char \fBisa_rev\fP"
.br
.ti -1c
.RI "unsigned char \fBgpr_size\fP"
.br
.ti -1c
.RI "unsigned char \fBcpr1_size\fP"
.br
.ti -1c
.RI "unsigned char \fBcpr2_size\fP"
.br
.ti -1c
.RI "unsigned char \fBfp_abi\fP"
.br
.ti -1c
.RI "Elf32_Word \fBisa_ext\fP"
.br
.ti -1c
.RI "Elf32_Word \fBases\fP"
.br
.ti -1c
.RI "Elf32_Word \fBflags1\fP"
.br
.ti -1c
.RI "Elf32_Word \fBflags2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
