.TH "Elf_Options" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Elf_Options
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBkind\fP"
.br
.ti -1c
.RI "unsigned char \fBsize\fP"
.br
.ti -1c
.RI "Elf32_Section \fBsection\fP"
.br
.ti -1c
.RI "Elf32_Word \fBinfo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
