.TH "encryption_info_command" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encryption_info_command
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBcmd\fP"
.br
.ti -1c
.RI "uint32_t \fBcmdsize\fP"
.br
.ti -1c
.RI "uint32_t \fBcryptoff\fP"
.br
.ti -1c
.RI "uint32_t \fBcryptsize\fP"
.br
.ti -1c
.RI "uint32_t \fBcryptid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
