.TH "inputs" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inputs \- Struct representing command-line inputs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <baseer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int * \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargs\fP"
.br
.ti -1c
.RI "int \fBinput_argc\fP"
.br
.ti -1c
.RI "char * \fBinput_args\fP [MAX_INPUT_ARGS]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct representing command-line inputs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
