.TH "linenoiseState" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linenoiseState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBin_completion\fP"
.br
.ti -1c
.RI "size_t \fBcompletion_idx\fP"
.br
.ti -1c
.RI "int \fBifd\fP"
.br
.ti -1c
.RI "int \fBofd\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBbuflen\fP"
.br
.ti -1c
.RI "const char * \fBprompt\fP"
.br
.ti -1c
.RI "size_t \fBplen\fP"
.br
.ti -1c
.RI "size_t \fBpos\fP"
.br
.ti -1c
.RI "size_t \fBoldpos\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBcols\fP"
.br
.ti -1c
.RI "size_t \fBoldrows\fP"
.br
.ti -1c
.RI "int \fBhistory_index\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
