.TH "mach_header_64" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mach_header_64
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmagic\fP"
.br
.ti -1c
.RI "cpu_type_t \fBcputype\fP"
.br
.ti -1c
.RI "cpu_subtype_t \fBcpusubtype\fP"
.br
.ti -1c
.RI "uint32_t \fBfiletype\fP"
.br
.ti -1c
.RI "uint32_t \fBncmds\fP"
.br
.ti -1c
.RI "uint32_t \fBsizeofcmds\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "uint32_t \fBreserved\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
