.TH "nlist" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlist
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBn_strx\fP"
.br
.ti -1c
.RI "uint8_t \fBn_type\fP"
.br
.ti -1c
.RI "uint8_t \fBn_sect\fP"
.br
.ti -1c
.RI "int16_t \fBn_desc\fP"
.br
.ti -1c
.RI "uint32_t \fBn_value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
