.TH "pos_name" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pos_name \- Maps a register/flag name to its position\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <debugger\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Maps a register/flag name to its position\&. 
.SH "Member Data Documentation"
.PP 
.SS "char* pos_name::name"
Name of register or flag 
.SS "int pos_name::pos"
Byte or bit offset 

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
