.TH "posix_header" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
posix_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [100]"
.br
.ti -1c
.RI "char \fBmode\fP [8]"
.br
.ti -1c
.RI "char \fBuid\fP [8]"
.br
.ti -1c
.RI "char \fBgid\fP [8]"
.br
.ti -1c
.RI "char \fBsize\fP [12]"
.br
.ti -1c
.RI "char \fBmtime\fP [12]"
.br
.ti -1c
.RI "char \fBchksum\fP [8]"
.br
.ti -1c
.RI "char \fBtypeflag\fP"
.br
.ti -1c
.RI "char \fBlinkname\fP [100]"
.br
.ti -1c
.RI "char \fBmagic\fP [6]"
.br
.ti -1c
.RI "char \fBversion\fP [2]"
.br
.ti -1c
.RI "char \fBuname\fP [32]"
.br
.ti -1c
.RI "char \fBgname\fP [32]"
.br
.ti -1c
.RI "char \fBdevmajor\fP [8]"
.br
.ti -1c
.RI "char \fBdevminor\fP [8]"
.br
.ti -1c
.RI "char \fBprefix\fP [155]"
.br
.ti -1c
.RI "char \fBpad\fP [12]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
