.TH "tests/test_hashmap.c" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/test_hashmap.c \- Unit tests for the b_hashmap module\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'test_framework\&.h'\fP
.br
\fR#include '\&.\&./modules/b_hashmap/b_hashmap\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (test_create_map)"
.br
.ti -1c
.RI "\fBTEST\fP (test_insert_and_get)"
.br
.ti -1c
.RI "\fBTEST\fP (test_get_nonexistent)"
.br
.ti -1c
.RI "\fBTEST\fP (test_hash_collision_handling)"
.br
.ti -1c
.RI "\fBTEST\fP (test_duplicate_key_insert)"
.br
.ti -1c
.RI "\fBTEST\fP (test_empty_key)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Unit tests for the b_hashmap module\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
