.TH "ud_itab_entry_operand" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ud_itab_entry_operand
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum ud_operand_code \fBtype\fP"
.br
.ti -1c
.RI "ud_operand_size_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
