.TH "ud_lval" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ud_lval
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBsbyte\fP"
.br
.ti -1c
.RI "uint8_t \fBubyte\fP"
.br
.ti -1c
.RI "int16_t \fBsword\fP"
.br
.ti -1c
.RI "uint16_t \fBuword\fP"
.br
.ti -1c
.RI "int32_t \fBsdword\fP"
.br
.ti -1c
.RI "uint32_t \fBudword\fP"
.br
.ti -1c
.RI "int64_t \fBsqword\fP"
.br
.ti -1c
.RI "uint64_t \fBuqword\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint16_t \fBseg\fP"
.br
.ti -1c
.RI "   uint32_t \fBoff\fP"
.br
.ti -1c
.RI "} \fBptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
