.TH "ud_optable.UdOptableXmlParser" 3 "Version 0.1.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ud_optable.UdOptableXmlParser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparseDef\fP (self, node)"
.br
.ti -1c
.RI "\fBparse\fP (self, xml, fn)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTlNode\fP = xmlDoc\&.firstChild"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
