.TH "utils/ui.h" 3 "Version 0.2.0" "Baseer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils/ui.h \- User interface utilities for Baseer\&.  

.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./baseer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_banner\fP (void)"
.br
.RI "Prints the Baseer banner\&. "
.ti -1c
.RI "void \fBprint_usage\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
User interface utilities for Baseer\&. 


.SH "Function Documentation"
.PP 
.SS "void print_banner (void )"

.PP
Prints the Baseer banner\&. Prints the Baseer banner\&.

.PP
Used when program is run with insufficient arguments or for branding\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Baseer from the source code\&.
